package com.rockandcode.cursos.domain.models

data class Course(
    val id: Int,
    val title: String,
    val subTitle: String,
    val description: String,
    val thumbnailUrl: String,
    val rating: Double,
    val ratingCount: Int = 0,
    val price: Double,
    val isFree: Boolean,
    val instructors: List<Instructor>,
    val categories: List<Category>,
    val schedule: List<Schedule>,
    val totalStudents: Int,
    val sections: List<CourseSection>,
    val documents: List<CourseDocument> = emptyList(),
    val level: CourseLevel,
    val features: List<CourseFeatureItem>,
    val requirements: List<String> = emptyList(),
    val author: Instructor? = instructors.firstOrNull(),
    val createdAt: String,
    val updatedAt: String,
    val topics: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
    val comments: List<Comment> = emptyList(),
    val hasCertificate: Boolean,
    val hasLifetimeAccess: Boolean,
)
