package com.rockandcode.cursos.domain.models

data class Course(
    val id: Int,
    val title: String,
    val subTitle: String = "",
    val description: String = "",
    val thumbnailUrl: String = "",
    val rating: Double = 0.0,
    val ratingCount: Int = 0,
    val price: Double = 0.0,
    val isFree: Boolean = false,
    val instructors: List<Instructor> = emptyList(),
    val categories: List<Category> = emptyList(),
    val schedule: List<Schedule> = emptyList(),
    val totalStudents: Int = 0,
    val sections: List<CourseSection> = emptyList(),
    val documents: List<CourseDocument> = emptyList(),
    val level: CourseLevel = CourseLevel(0, "Desconocido", "Nivel no especificado"),
    val features: List<CourseFeatureItem> = emptyList(),
    val requirements: List<String> = emptyList(),
    val author: Instructor? = instructors.firstOrNull(),
    val createdAt: String = "",
    val updatedAt: String = "",
    val topics: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
    val comments: List<Comment> = emptyList(),
    val hasCertificate: Boolean = false,
    val hasLifetimeAccess: Boolean = false,
)
