package com.rockandcode.cursos.domain.models

data class Course(
    val id: Int,
    val title: String,
    val description: String,
    val thumbnailUrl: String,
    val rating: Double,
    val ratingCount: Int = 0,
    val price: Double,
    val isFree: Boolean,
    val instructors: List<Instructor>,
    val categories: List<Category>,
    val schedule: List<Schedule>,
    val totalStudents: Int,
    val items: List<VideoItem>,
    val documents: List<CourseDocument> = emptyList(),
    val level: CourseLevel,
    val includes: List<CourseIncludeItem>,
    val requirements: String,
    val author: Instructor? = instructors.firstOrNull(),
    val createdAt: String,
    val updatedAt: String,
    val topics: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
)
